# docker-compose.yml
version: "3.8"

services:
  postgres1:
    image: postgres:15
    container_name: postgres1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: shard1

  postgres2:
    image: postgres:15
    container_name: postgres2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: shard2

  postgres3:
    image: postgres:15
    container_name: postgres3
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: shard3

  adminer:
    image: adminer:4
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres-primary
    depends_on:
      - postgres1
      - postgres2
      - postgres3